# Generated by Django 3.0.5 on 2022-12-02 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('business_system', models.CharField(max_length=255)),
                ('room_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(choices=[('2', 2), ('3', 3)])),
                ('attendance_1', models.BooleanField(default=False)),
                ('attendance_2', models.BooleanField(default=False)),
                ('attendance_3', models.BooleanField(default=False)),
                ('attendance_4', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Team')),
            ],
        ),
    ]
