# Generated by Django 3.0.5 on 2022-12-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20221202_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='room_no',
            field=models.CharField(choices=[('C107', 'C107'), ('C108', 'C108'), ('C109', 'C109'), ('C110', 'C110'), ('C111', 'C111'), ('C121', 'C121'), ('C225', 'C225'), ('C307', 'C307'), ('C308', 'C308'), ('C309', 'C309'), ('C321B1', 'C321B1'), ('C321B2', 'C321B2'), ('C325', 'C325'), ('C406', 'C406'), ('C407', 'C407'), ('C410', 'C410'), ('C411', 'C411'), ('C421A', 'C421A'), ('C422', 'C422'), ('C423', 'C423'), ('C425', 'C425'), ('C525', 'C525'), ('C625', 'C625'), ('GroundFloorLab', 'GroundFloorLab'), ('FirstFloorLab', 'FirstFloorLab'), ('SecondFloorLab', 'SecondFloorLab'), ('ThirdFloorLab', 'ThirdFloorLab'), ('FourthFloorLab', 'FourthFloorLab'), ('SixthFloorLab', 'SixthFloorLab')], max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_no',
            field=models.CharField(max_length=250),
        ),
    ]
